# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: _columnar_write.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    '_columnar_write.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15_columnar_write.proto\x12\x10nominal_columnar\"i\n\tTimestamp\x12\x14\n\x07seconds\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x12\n\x05nanos\x18\x02 \x01(\x03H\x01\x88\x01\x01\x12\x12\n\x05picos\x18\x03 \x01(\x05H\x02\x88\x01\x01\x42\n\n\x08_secondsB\x08\n\x06_nanosB\x08\n\x06_picos\"_\n\x13WriteBatchesRequest\x12/\n\x07\x62\x61tches\x18\x01 \x03(\x0b\x32\x1e.nominal_columnar.RecordsBatch\x12\x17\n\x0f\x64\x61ta_source_rid\x18\x02 \x01(\t\"\xae\x01\n\x0cRecordsBatch\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x36\n\x04tags\x18\x02 \x03(\x0b\x32(.nominal_columnar.RecordsBatch.TagsEntry\x12(\n\x06points\x18\x03 \x01(\x0b\x32\x18.nominal_columnar.Points\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa1\x02\n\x06Points\x12/\n\ntimestamps\x18\x01 \x03(\x0b\x32\x1b.nominal_columnar.Timestamp\x12\x37\n\rdouble_points\x18\x02 \x01(\x0b\x32\x1e.nominal_columnar.DoublePointsH\x00\x12\x37\n\rstring_points\x18\x03 \x01(\x0b\x32\x1e.nominal_columnar.StringPointsH\x00\x12\x31\n\nint_points\x18\x05 \x01(\x0b\x32\x1b.nominal_columnar.IntPointsH\x00\x12\x37\n\ruint64_points\x18\x08 \x01(\x0b\x32\x1e.nominal_columnar.Uint64PointsH\x00\x42\x08\n\x06points\"\x1e\n\x0c\x44oublePoints\x12\x0e\n\x06points\x18\x01 \x03(\x01\"\x1e\n\x0cStringPoints\x12\x0e\n\x06points\x18\x01 \x03(\t\"\x1b\n\tIntPoints\x12\x0e\n\x06points\x18\x01 \x03(\x03\"\x1e\n\x0cUint64Points\x12\x0e\n\x06points\x18\x01 \x03(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '_columnar_write_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECORDSBATCH_TAGSENTRY']._loaded_options = None
  _globals['_RECORDSBATCH_TAGSENTRY']._serialized_options = b'8\001'
  _globals['_TIMESTAMP']._serialized_start=43
  _globals['_TIMESTAMP']._serialized_end=148
  _globals['_WRITEBATCHESREQUEST']._serialized_start=150
  _globals['_WRITEBATCHESREQUEST']._serialized_end=245
  _globals['_RECORDSBATCH']._serialized_start=248
  _globals['_RECORDSBATCH']._serialized_end=422
  _globals['_RECORDSBATCH_TAGSENTRY']._serialized_start=379
  _globals['_RECORDSBATCH_TAGSENTRY']._serialized_end=422
  _globals['_POINTS']._serialized_start=425
  _globals['_POINTS']._serialized_end=714
  _globals['_DOUBLEPOINTS']._serialized_start=716
  _globals['_DOUBLEPOINTS']._serialized_end=746
  _globals['_STRINGPOINTS']._serialized_start=748
  _globals['_STRINGPOINTS']._serialized_end=778
  _globals['_INTPOINTS']._serialized_start=780
  _globals['_INTPOINTS']._serialized_end=807
  _globals['_UINT64POINTS']._serialized_start=809
  _globals['_UINT64POINTS']._serialized_end=839
# @@protoc_insertion_point(module_scope)
