import importlib.metadata

from nominal import ts
from nominal.core import (
    Asset,
    Attachment,
    Channel,
    Checklist,
    CheckViolation,
    Connection,
    DataReview,
    DataReviewBuilder,
    Dataset,
    DatasetFile,
    NominalClient,
    Run,
    User,
    Video,
    Workbook,
    Workspace,
    WorkspaceSearchType,
    WriteStream,
)
from nominal.nominal import (
    create_asset,
    create_run,
    create_run_csv,
    create_streaming_connection,
    create_workbook_from_template,
    data_review_builder,
    download_attachment,
    get_asset,
    get_attachment,
    get_checklist,
    get_connection,
    get_data_review,
    get_dataset,
    get_default_client,
    get_run,
    get_video,
    list_streaming_checklists,
    search_assets,
    search_runs,
    set_base_url,
    set_token,
    upload_attachment,
    upload_csv,
    upload_mcap_video,
    upload_pandas,
    upload_polars,
    upload_tdms,
    upload_video,
)

__all__ = [
    "__version__",
    "Asset",
    "Attachment",
    "Channel",
    "Checklist",
    "CheckViolation",
    "Connection",
    "create_asset",
    "create_run_csv",
    "create_run",
    "create_streaming_connection",
    "create_workbook_from_template",
    "data_review_builder",
    "DataReview",
    "DataReviewBuilder",
    "Dataset",
    "DatasetFile",
    "download_attachment",
    "get_asset",
    "get_attachment",
    "get_checklist",
    "get_connection",
    "get_data_review",
    "get_dataset",
    "get_default_client",
    "get_run",
    "get_video",
    "list_streaming_checklists",
    "NominalClient",
    "Run",
    "search_assets",
    "search_runs",
    "set_base_url",
    "set_token",
    "ts",
    "upload_attachment",
    "upload_csv",
    "upload_mcap_video",
    "upload_pandas",
    "upload_polars",
    "upload_tdms",
    "upload_video",
    "User",
    "Video",
    "Workbook",
    "Workspace",
    "WorkspaceSearchType",
    "WriteStream",
]


try:
    __version__ = importlib.metadata.version("nominal")
except importlib.metadata.PackageNotFoundError:
    __version__ = "unknown"
del importlib
