"""Shared fixtures for migration e2e tests.

Connection setup
----------------
Migration tests require two Nominal clients:
- ``source_client``: the environment to migrate *from* (e.g. production).
  Configured via ``--source-profile`` or ``--source-auth-token`` + ``--source-base-url``.
- ``dest_client``: the environment to migrate *to* (e.g. staging).
  Configured via ``--dest-profile`` or ``--dest-auth-token`` + ``--dest-base-url``.
  Falls back to the global ``--profile`` / ``--auth-token`` + ``--base-url`` options for
  backwards compatibility.

Teardown helpers
----------------
``register_cleanup`` — a function-scoped fixture that schedules a callable for execution
after each test, even on failure. Pass any no-arg callable (typically ``obj.archive``) to
register it::

    register_cleanup(obj.archive)

See https://docs.pytest.org/en/stable/reference/reference.html#request for details on the
underlying pytest ``request`` fixture.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from io import BytesIO
from typing import Callable
from uuid import uuid4

import pytest

from nominal.core import NominalClient
from nominal.core.dataset import Dataset
from nominal.experimental.migration.migration_state import MigrationState
from nominal.experimental.migration.migrator.context import MigrationContext
from tests.e2e import POLL_INTERVAL

RegisterCleanup = Callable[[Callable[[], None]], None]

# --- channel-sync e2e shared constants ---------------------------------------------------------
# The two-tag source fixture below carries the same channels under two ``asset_id`` tag values, each
# generated by :func:`make_sync_csv` (not the shared ``csv_data`` literals -- those stay small/fast for
# the rest of the suite). Layout, in 1-hour detection buckets tiled forward from the window start:
#
#   bucket:  1  2  3  4  5  6  7  8  9
#   A:       A  A  A  AB AB AB             sync_csv_a, asset_id=A  (buckets 1-6)
#   B:                AB AB AB B  B  B     sync_csv_b, asset_id=B  (buckets 4-9)
#
# A and B partially overlap (overlap = half the buckets per file = 3, buckets 4-6). The sync window
# spans all 9 buckets, so a tag-filtered sync can only exclude the other tag via the tag filter (never
# the time window). In the overlap A and B share timestamps but carry disjoint value ranges (A
# temperature 20-29, B 30-39), so a cross-tag leak surfaces as out-of-range values.
SYNC_TAG_KEY = "asset_id"
SYNC_TAG_A = "A"
SYNC_TAG_B = "B"

# Detection bucket (1 hour, matching the ChannelSyncOptions.bucket default) and the source-data shape.
BUCKET_NS = 3_600_000_000_000
BUCKET_MINUTES = 60
POINTS_PER_BUCKET = 12  # rows per detection bucket (kept modest so streaming settles quickly in e2e)
SPACING_MINUTES = BUCKET_MINUTES // POINTS_PER_BUCKET  # 5; POINTS_PER_BUCKET must divide 60 evenly
BUCKETS_PER_FILE = 6
OVERLAP_BUCKETS = BUCKETS_PER_FILE // 2  # 3: overlap is half the buckets per file
B_START_BUCKET = BUCKETS_PER_FILE - OVERLAP_BUCKETS  # 3: B begins this many buckets after A
TOTAL_BUCKETS = 2 * BUCKETS_PER_FILE - OVERLAP_BUCKETS  # 9
FILE_POINT_COUNT = BUCKETS_PER_FILE * POINTS_PER_BUCKET  # 72 points per tag
HALF_POINT_COUNT = FILE_POINT_COUNT // 2  # 36: A's first three buckets

# Non-round start offset so no row lands on a wall-clock hour boundary (buckets tile forward from here).
SYNC_START_DT = datetime(2024, 9, 5, 18, 7, 33, tzinfo=timezone.utc)
SYNC_WINDOW_START = int(SYNC_START_DT.timestamp()) * 1_000_000_000
SYNC_WINDOW_END = SYNC_WINDOW_START + TOTAL_BUCKETS * BUCKET_NS


def make_sync_csv(*, start: datetime, count: int, temp_base: int, humidity_base: int) -> bytes:
    """Build a sensor CSV (timestamp, relative_minutes, temperature, humidity).

    ``count`` rows spaced ``SPACING_MINUTES`` apart from ``start`` (so ``POINTS_PER_BUCKET`` land in
    each one-hour detection bucket). ``temp_base``/``humidity_base`` set each tag's distinct value
    range (each cycles over a 10-wide band), so a cross-tag leak shows up as out-of-range values.
    """
    lines = ["timestamp,relative_minutes,temperature,humidity"]
    for i in range(count):
        minutes = i * SPACING_MINUTES
        ts = (start + timedelta(minutes=minutes)).strftime("%Y-%m-%dT%H:%M:%SZ")
        lines.append(f"{ts},{minutes},{temp_base + i % 10},{humidity_base - i % 10}")
    return ("\n".join(lines) + "\n").encode()

# --- channel-sync e2e: adversarial channel-type stress data ------------------------------------
# A generated dataset with the channel types that are annoying to migrate, so the hard export/stream
# code paths run end-to-end (not just the numeric happy path). Generated rather than a literal so the
# high-cardinality column is genuinely high-cardinality.
STRESS_ENUM_VALUES = ("nominal", "warning", "fault")
# Row count: high enough that the unique-per-row STRING column overflows the backend's enum-category
# limit (Compute:TooManyCategories) within a single bucket, forcing that channel onto the non-precise
# recursive-halving export fallback. The default 1-hour detection bucket keeps every row in one bucket
# (the window below is ~33 min) so the categories accumulate there. Bump this if a run shows the
# high-cardinality channel was still detected precise.
STRESS_ROWS = 2000
_STRESS_START = datetime(2024, 9, 5, 18, 0, tzinfo=timezone.utc)
STRESS_WINDOW_START = int(_STRESS_START.timestamp()) * 1_000_000_000
# One second per row; the window is half-open and ends one second past the last row.
STRESS_WINDOW_END = STRESS_WINDOW_START + STRESS_ROWS * 1_000_000_000


def make_stress_csv(rows: int = STRESS_ROWS) -> bytes:
    """Build a CSV exercising each migration-hard channel type, one row per second from 18:00.

    Columns:
    - ``hi_card_str``: a unique value per row (high-cardinality STRING -> TooManyCategories ->
      non-precise presence probe + per-channel recursive-halving export fallback).
    - ``enum_str``: a small repeating label set (low-cardinality enum STRING -> precise bucketed-enum
      counting; numeric-looking labels stay strings on re-read).
    - ``int_ch``: whole numbers (INT -> exercises the Float64->int recast so values land as INT).
    - ``dbl_ch``: integral-looking floats like ``42.0`` (DOUBLE -> exercises the Float64 guard so a
      double is not re-inferred/created as INT in the destination).
    """
    from datetime import timedelta

    lines = ["timestamp,hi_card_str,enum_str,int_ch,dbl_ch"]
    for i in range(rows):
        ts = (_STRESS_START + timedelta(seconds=i)).strftime("%Y-%m-%dT%H:%M:%SZ")
        lines.append(f"{ts},id_{i},{STRESS_ENUM_VALUES[i % 3]},{i % 100},{float(i % 50)}")
    return ("\n".join(lines) + "\n").encode()


# Expected destination channel types after a correct round-trip.
STRESS_CHANNEL_TYPES = {
    "hi_card_str": "STRING",
    "enum_str": "STRING",
    "int_ch": "INT",
    "dbl_ch": "DOUBLE",
}


def pytest_addoption(parser):
    """Register source and destination environment CLI options."""
    parser.addoption("--source-profile", default=None, help="Source Nominal profile name (e.g. production)")
    parser.addoption("--source-auth-token", default=None, help="Source auth token (used with --source-base-url)")
    parser.addoption(
        "--source-base-url", default="https://api.gov.nominal.io/api", help="Source base URL (default: production)"
    )
    parser.addoption("--dest-profile", default=None, help="Destination Nominal profile name (e.g. staging)")
    parser.addoption("--dest-auth-token", default=None, help="Destination auth token (used with --dest-base-url)")
    parser.addoption(
        "--dest-base-url",
        default="https://api-staging.gov.nominal.io/api",
        help="Destination base URL (default: staging)",
    )
    parser.addoption(
        "--impersonation-source-user-rid",
        default=None,
        help="Source user RID for impersonation e2e test (must match the creator of source resources)",
    )
    parser.addoption(
        "--impersonation-dest-user-rid",
        default=None,
        help="Destination user RID to impersonate in impersonation e2e test",
    )


@pytest.fixture(scope="session")
def source_client(pytestconfig) -> NominalClient:
    """Build a NominalClient for the migration source environment (e.g. production)."""
    profile = pytestconfig.getoption("source_profile")
    if profile is not None:
        print(f"Using source NominalClient.from_profile({profile!r})")
        return NominalClient.from_profile(profile)
    auth_token = pytestconfig.getoption("source_auth_token")
    if auth_token is None:
        raise pytest.UsageError(
            "Either --source-profile or --source-auth-token must be provided for migration source environment"
        )
    base_url = pytestconfig.getoption("source_base_url")
    print(f"Using source NominalClient.create(base_url={base_url!r})")
    return NominalClient.create(base_url=base_url, token=auth_token)


@pytest.fixture(scope="session")
def dest_client(pytestconfig) -> NominalClient:
    """Build a NominalClient for the migration destination environment (e.g. staging).

    ``--dest-profile`` takes precedence; falls back to the global ``--profile`` for
    backwards compatibility with existing invocations.
    """
    profile = pytestconfig.getoption("dest_profile") or pytestconfig.getoption("profile")
    if profile is not None:
        print(f"Using dest NominalClient.from_profile({profile!r})")
        return NominalClient.from_profile(profile)
    auth_token = pytestconfig.getoption("dest_auth_token") or pytestconfig.getoption("auth_token")
    if auth_token is None:
        raise pytest.UsageError(
            "Either --dest-profile or --dest-auth-token must be provided for migration destination environment"
        )
    base_url = pytestconfig.getoption("dest_base_url") or pytestconfig.getoption("base_url")
    print(f"Using dest NominalClient.create(base_url={base_url!r})")
    return NominalClient.create(base_url=base_url, token=auth_token)


@pytest.fixture
def register_cleanup(request) -> RegisterCleanup:
    """Schedule a callable to run after the current test, even on failure.

    Usage::

        register_cleanup(obj.archive)
    """

    def _register(fn: Callable[[], None]) -> None:
        request.addfinalizer(fn)

    return _register


@pytest.fixture
def migration_ctx(dest_client: NominalClient) -> MigrationContext:
    """A fresh MigrationContext with an empty MigrationState for each test."""
    return MigrationContext(
        destination_client=dest_client,
        migration_state=MigrationState(rid_mapping={}),
    )


@pytest.fixture
def ingested_source_dataset(
    source_client: NominalClient, csv_data: bytes, register_cleanup: RegisterCleanup
) -> Dataset:
    """A dataset on the source client, fully ingested from csv_data."""
    ds = source_client.create_dataset(f"migration-e2e-source-{uuid4().hex[:8]}")
    register_cleanup(ds.archive)
    ds.add_from_io(BytesIO(csv_data), "timestamp", "iso_8601").poll_until_ingestion_completed(interval=POLL_INTERVAL)
    return ds


@pytest.fixture
def sync_csv_a() -> bytes:
    """Tag-A source CSV: 360 points (buckets 1-6), temperature 20-29 / humidity 41-50."""
    return make_sync_csv(start=SYNC_START_DT, count=FILE_POINT_COUNT, temp_base=20, humidity_base=50)


@pytest.fixture
def sync_csv_b() -> bytes:
    """Tag-B source CSV: 360 points (buckets 4-9), temperature 30-39 / humidity 31-40.

    Starts ``B_START_BUCKET`` buckets after A so its first three buckets overlap A's last three.
    """
    start = SYNC_START_DT + timedelta(minutes=B_START_BUCKET * BUCKET_MINUTES)
    return make_sync_csv(start=start, count=FILE_POINT_COUNT, temp_base=30, humidity_base=40)


@pytest.fixture
def source_dataset_two_tags(
    source_client: NominalClient,
    sync_csv_a: bytes,
    sync_csv_b: bytes,
    register_cleanup: RegisterCleanup,
) -> Dataset:
    """A source dataset carrying the same channels under two ``asset_id`` tag values.

    ``add_from_io(..., tags=...)`` applies a tag uniformly to every point in a file, so ingesting the
    two CSVs with distinct tag values yields the same channels (temperature, humidity,
    relative_minutes) under ``asset_id=A`` and ``asset_id=B``. The two tags partially overlap in time
    (see the layout above) with disjoint value ranges, so a tag-filter leak is visible while the window
    spans both and never does the filtering itself.
    """
    ds = source_client.create_dataset(f"channel-sync-e2e-source-{uuid4().hex[:8]}")
    register_cleanup(ds.archive)
    ds.add_from_io(
        BytesIO(sync_csv_a), "timestamp", "iso_8601", tags={SYNC_TAG_KEY: SYNC_TAG_A}
    ).poll_until_ingestion_completed(interval=POLL_INTERVAL)
    ds.add_from_io(
        BytesIO(sync_csv_b), "timestamp", "iso_8601", tags={SYNC_TAG_KEY: SYNC_TAG_B}
    ).poll_until_ingestion_completed(interval=POLL_INTERVAL)
    return ds


@pytest.fixture
def dest_dataset(dest_client: NominalClient, register_cleanup: RegisterCleanup) -> Dataset:
    """An empty dataset on the destination client; the write stream auto-creates series on first write."""
    ds = dest_client.create_dataset(f"channel-sync-e2e-dest-{uuid4().hex[:8]}")
    register_cleanup(ds.archive)
    return ds


@pytest.fixture
def source_dataset_stress(source_client: NominalClient, register_cleanup: RegisterCleanup) -> Dataset:
    """A source dataset of the migration-hard channel types (see :func:`make_stress_csv`).

    Untagged: this fixture exercises the channel-type code paths, while ``source_dataset_two_tags``
    covers the tag-filter dimension. Sync over ``[STRESS_WINDOW_START, STRESS_WINDOW_END)``.
    """
    ds = source_client.create_dataset(f"channel-sync-e2e-stress-{uuid4().hex[:8]}")
    register_cleanup(ds.archive)
    ds.add_from_io(BytesIO(make_stress_csv()), "timestamp", "iso_8601").poll_until_ingestion_completed(
        interval=POLL_INTERVAL
    )
    return ds
