site_name: "Nominal Python SDK: Function Reference"
repo_url: "https://github.com/nominal-io/nominal-client"
repo_name: "nominal-io/nominal-client"
site_dir: site
watch: [mkdocs.yml, ../README.md, ../CHANGELOG.md, ../nominal]
copyright: Copyright &copy; 2024 Nominal, Inc.
edit_uri: edit/main/docs/
docs_dir: src

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

extra_css:
  - css/mkdocstrings.css
  - css/slate-muted.css

nav:
  - Home:
      - Overview: index.md
      - Changelog: changelog.md
      - License: license.md
  - Reference:
      - High-level SDK: reference/toplevel.md
      - Timestamps: reference/ts.md
      - Core SDK: reference/core.md
      - Exceptions: reference/exceptions.md
      - nom cli: reference/nom-cli.md
      - Third Party:
        - pandas: reference/thirdparty/pandas.md
        - tdms: reference/thirdparty/tdms.md
      - Experimental:
        - Video Processing: reference/experimental/video_processing.md
  - Development:
      - Contributing: contributing.md
  - Documentation: https://docs.nominal.io/core/sdk/python-client/quickstart
  - Nominal: https://nominal.io

theme:
  name: material
  palette:
    scheme: default
  logo: logo.svg
  favicon: favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to muted dark mode
    - scheme: slate-muted
      toggle:
        icon: material/weather-night-partly-cloudy
        name: Switch to light mode

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.magiclink
  - pymdownx.snippets:
      base_path:
        - !relative $config_dir
        - CHANGELOG.md
        - CONTRIBUTING.md
        - LICENSE
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      toc_depth: 3
      permalink: "¤"
  - attr_list
  - mkdocs-click

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: ["!^_"]
            heading_level: 1
            inherited_members: true
            show_if_no_docstring: true
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            line_length: 72
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            show_source: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nominal-io
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/nominal/
